apiVersion: v1
kind: PersistentVolume
metadata:
  name: volNNN
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce     
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/volNNN
